/* Generated By:JavaCC: Do not edit this line. GenTokerConstants.java */
package org.mitre.jcarafe.lexer;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GenTokerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ST = 1;
  /** RegularExpression Id. */
  int EN = 2;
  /** RegularExpression Id. */
  int ENST = 3;
  /** RegularExpression Id. */
  int ENDPUNCT = 4;
  /** RegularExpression Id. */
  int WHITEEND = 5;
  /** RegularExpression Id. */
  int TAGEND = 6;
  /** RegularExpression Id. */
  int TAGSTART = 7;
  /** RegularExpression Id. */
  int URL = 8;
  /** RegularExpression Id. */
  int ABBREV = 9;
  /** RegularExpression Id. */
  int PUNCT = 10;
  /** RegularExpression Id. */
  int TOK = 11;
  /** RegularExpression Id. */
  int WHITE = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"<\"",
    "\">\"",
    "\"</\"",
    "<ENDPUNCT>",
    "<WHITEEND>",
    "<TAGEND>",
    "<TAGSTART>",
    "<URL>",
    "<ABBREV>",
    "<PUNCT>",
    "<TOK>",
    "<WHITE>",
  };

}
