/* Generated By:JavaCC: Do not edit this line. GenTokerTokenManager.java */
package org.mitre.jcarafe.lexer;

/** Token Manager. */
public class GenTokerTokenManager implements GenTokerConstants
{

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private int jjMoveStringLiteralDfa0_0()
{
   return jjMoveNfa_0(1, 0);
}
static final long[] jjbitVec0 = {
   0xfffffffffffffffeL, 0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec2 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 345;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((0x63ffa038ffffd9ffL & l) != 0L)
                  {
                     if (kind > 11)
                        kind = 11;
                     jjCheckNAdd(51);
                  }
                  else if ((0x2400L & l) != 0L)
                  {
                     if (kind > 12)
                        kind = 12;
                  }
                  else if ((0x100000200L & l) != 0L)
                  {
                     if (kind > 12)
                        kind = 12;
                     jjCheckNAdd(52);
                  }
                  else if ((0x8000400200000000L & l) != 0L)
                  {
                     if (kind > 4)
                        kind = 4;
                     jjCheckNAdd(0);
                  }
                  else if (curChar == 39)
                     jjAddStates(0, 6);
                  else if (curChar == 38)
                     jjstateSet[jjnewStateCnt++] = 43;
                  else if (curChar == 60)
                     jjCheckNAdd(10);
                  if ((0x3ff700000000000L & l) != 0L)
                     jjCheckNAddTwoStates(48, 49);
                  else if (curChar == 33)
                     jjCheckNAddTwoStates(344, 340);
                  else if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 53;
                  else if (curChar == 36)
                     jjCheckNAddTwoStates(48, 49);
                  else if (curChar == 60)
                     jjstateSet[jjnewStateCnt++] = 5;
                  else if (curChar == 10)
                     jjCheckNAddTwoStates(3, 4);
                  else if (curChar == 63)
                     jjCheckNAddTwoStates(342, 340);
                  if ((0xac005fc600000000L & l) != 0L)
                  {
                     if (kind > 10)
                        kind = 10;
                     jjCheckNAdd(41);
                  }
                  else if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 11)
                        kind = 11;
                     jjCheckNAddStates(7, 11);
                  }
                  else if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 2;
                  if (curChar == 46)
                     jjCheckNAddTwoStates(339, 340);
                  break;
               case 0:
                  if ((0x8000400200000000L & l) == 0L)
                     break;
                  if (kind > 4)
                     kind = 4;
                  jjCheckNAdd(0);
                  break;
               case 2:
                  if (curChar == 10)
                     jjCheckNAddTwoStates(3, 4);
                  break;
               case 3:
                  if (curChar == 13)
                     jjCheckNAdd(4);
                  break;
               case 4:
                  if (curChar != 10)
                     break;
                  if (kind > 5)
                     kind = 5;
                  jjCheckNAddTwoStates(3, 4);
                  break;
               case 5:
                  if (curChar == 47)
                     jjCheckNAdd(6);
                  break;
               case 6:
                  if ((0xafffffffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(6, 7);
                  break;
               case 7:
                  if (curChar == 62 && kind > 6)
                     kind = 6;
                  break;
               case 8:
                  if (curChar == 60)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 9:
                  if (curChar == 60)
                     jjCheckNAdd(10);
                  break;
               case 10:
                  if ((0xafffffffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(10, 11);
                  break;
               case 11:
                  if (curChar == 62 && kind > 7)
                     kind = 7;
                  break;
               case 13:
                  if (curChar == 58)
                     jjAddStates(12, 13);
                  break;
               case 14:
                  if (curChar == 47)
                     jjCheckNAddStates(14, 16);
                  break;
               case 16:
                  if (curChar == 46)
                     jjCheckNAdd(17);
                  break;
               case 17:
                  if ((0xaffffcfeffffd9ffL & l) != 0L)
                     jjCheckNAddTwoStates(17, 18);
                  break;
               case 18:
                  if ((0x23ffac78ffffd9ffL & l) == 0L)
                     break;
                  if (kind > 8)
                     kind = 8;
                  jjCheckNAdd(18);
                  break;
               case 19:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(17, 19);
                  break;
               case 20:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(16);
                  break;
               case 21:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(20, 16);
                  break;
               case 24:
                  if ((0x3ff600000000000L & l) != 0L)
                     jjCheckNAddTwoStates(24, 25);
                  break;
               case 25:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 26;
                  break;
               case 28:
                  if (curChar == 47)
                     jjCheckNAdd(17);
                  break;
               case 31:
                  if (curChar == 47)
                     jjCheckNAddStates(20, 22);
                  break;
               case 32:
                  if (curChar == 47)
                     jjCheckNAddTwoStates(23, 24);
                  break;
               case 33:
                  if ((0x3ff002000000000L & l) != 0L)
                     jjCheckNAddTwoStates(23, 24);
                  break;
               case 34:
                  if (curChar == 46 && kind > 9)
                     kind = 9;
                  break;
               case 36:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 41:
                  if ((0xac005fc600000000L & l) == 0L)
                     break;
                  if (kind > 10)
                     kind = 10;
                  jjCheckNAdd(41);
                  break;
               case 42:
                  if (curChar == 38)
                     jjstateSet[jjnewStateCnt++] = 43;
                  break;
               case 44:
                  if (curChar == 59 && kind > 11)
                     kind = 11;
                  break;
               case 46:
                  if (curChar == 46 && kind > 11)
                     kind = 11;
                  break;
               case 47:
                  if (curChar == 36)
                     jjCheckNAddTwoStates(48, 49);
                  break;
               case 48:
                  if ((0x3ff700000000000L & l) != 0L)
                     jjCheckNAddTwoStates(48, 49);
                  break;
               case 49:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddTwoStates(49, 50);
                  break;
               case 50:
                  if (curChar == 37 && kind > 11)
                     kind = 11;
                  break;
               case 51:
                  if ((0x63ffa038ffffd9ffL & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAdd(51);
                  break;
               case 52:
                  if ((0x100000200L & l) == 0L)
                     break;
                  if (kind > 12)
                     kind = 12;
                  jjCheckNAdd(52);
                  break;
               case 53:
                  if (curChar == 10 && kind > 12)
                     kind = 12;
                  break;
               case 54:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 53;
                  break;
               case 55:
                  if ((0x2400L & l) != 0L && kind > 12)
                     kind = 12;
                  break;
               case 56:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddStates(7, 11);
                  break;
               case 57:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(58, 61);
                  break;
               case 58:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 59;
                  break;
               case 59:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 60;
                  break;
               case 60:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(61);
                  break;
               case 62:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 63;
                  break;
               case 64:
                  if (curChar == 39)
                     jjAddStates(0, 6);
                  break;
               case 282:
                  if (curChar == 32 && kind > 9)
                     kind = 9;
                  break;
               case 283:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 282;
                  break;
               case 337:
                  if (curChar == 46)
                     jjCheckNAddTwoStates(339, 340);
                  break;
               case 338:
                  if (curChar == 39 && kind > 4)
                     kind = 4;
                  break;
               case 339:
               case 342:
               case 344:
                  if (curChar == 39)
                     jjCheckNAdd(338);
                  break;
               case 340:
                  if (curChar == 34 && kind > 4)
                     kind = 4;
                  break;
               case 341:
                  if (curChar == 63)
                     jjCheckNAddTwoStates(342, 340);
                  break;
               case 343:
                  if (curChar == 33)
                     jjCheckNAddTwoStates(344, 340);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((0xd7fffffed7ffffffL & l) != 0L)
                  {
                     if (kind > 11)
                        kind = 11;
                     jjCheckNAdd(51);
                  }
                  if ((0x7fffffffffffffeL & l) != 0L)
                     jjCheckNAdd(46);
                  if ((0x7fffffe00000000L & l) != 0L)
                     jjCheckNAddTwoStates(12, 13);
                  else if ((0x3800000128000000L & l) != 0L)
                  {
                     if (kind > 10)
                        kind = 10;
                     jjCheckNAdd(41);
                  }
                  else if (curChar == 86)
                     jjAddStates(23, 24);
                  else if (curChar == 84)
                     jjAddStates(25, 26);
                  else if (curChar == 79)
                     jjAddStates(27, 30);
                  else if (curChar == 78)
                     jjAddStates(31, 33);
                  else if (curChar == 75)
                     jjAddStates(34, 35);
                  else if (curChar == 70)
                     jjAddStates(36, 37);
                  else if (curChar == 87)
                     jjAddStates(38, 41);
                  else if (curChar == 83)
                     jjAddStates(42, 52);
                  else if (curChar == 82)
                     jjAddStates(53, 55);
                  else if (curChar == 80)
                     jjAddStates(56, 62);
                  else if (curChar == 74)
                     jjAddStates(63, 67);
                  else if (curChar == 66)
                     jjAddStates(68, 71);
                  else if (curChar == 76)
                     jjAddStates(72, 75);
                  else if (curChar == 73)
                     jjAddStates(76, 79);
                  else if (curChar == 67)
                     jjAddStates(80, 96);
                  else if (curChar == 65)
                     jjAddStates(97, 103);
                  else if (curChar == 71)
                     jjAddStates(104, 110);
                  else if (curChar == 68)
                     jjAddStates(111, 116);
                  else if (curChar == 77)
                     jjAddStates(117, 134);
                  else if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 39;
                  else if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 36;
                  break;
               case 6:
                  jjAddStates(135, 136);
                  break;
               case 10:
                  jjAddStates(137, 138);
                  break;
               case 12:
                  if ((0x7fffffe00000000L & l) != 0L)
                     jjCheckNAddTwoStates(12, 13);
                  break;
               case 15:
                  if (curChar == 119)
                     jjAddStates(139, 140);
                  break;
               case 17:
                  jjCheckNAddTwoStates(17, 18);
                  break;
               case 18:
                  if ((0xd7fffffed7ffffffL & l) == 0L)
                     break;
                  if (kind > 8)
                     kind = 8;
                  jjCheckNAdd(18);
                  break;
               case 22:
                  if (curChar == 119)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 23:
                  if (curChar == 119)
                     jjstateSet[jjnewStateCnt++] = 22;
                  break;
               case 24:
                  if ((0x7fffffe00000000L & l) != 0L)
                     jjCheckNAddTwoStates(24, 25);
                  break;
               case 26:
                  if ((0x7fffffe00000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 27;
                  break;
               case 27:
                  if ((0x7fffffe00000000L & l) != 0L)
                     jjCheckNAddTwoStates(28, 29);
                  break;
               case 29:
                  if ((0x7fffffe00000000L & l) != 0L)
                     jjCheckNAddTwoStates(30, 28);
                  break;
               case 30:
                  if ((0x7fffffe00000000L & l) != 0L)
                     jjCheckNAdd(28);
                  break;
               case 33:
                  if ((0x7fffffe00000000L & l) != 0L)
                     jjCheckNAddTwoStates(23, 24);
                  break;
               case 35:
               case 83:
               case 85:
                  if (curChar == 83)
                     jjCheckNAdd(34);
                  break;
               case 37:
                  if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 36;
                  break;
               case 38:
               case 102:
               case 117:
               case 125:
               case 129:
               case 197:
               case 235:
               case 237:
               case 256:
               case 269:
               case 308:
               case 329:
                  if (curChar == 110)
                     jjCheckNAdd(34);
                  break;
               case 39:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 38;
                  break;
               case 40:
                  if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 39;
                  break;
               case 41:
                  if ((0x3800000128000000L & l) == 0L)
                     break;
                  if (kind > 10)
                     kind = 10;
                  jjCheckNAdd(41);
                  break;
               case 43:
                  if ((0x7fffffffffffffeL & l) != 0L)
                     jjAddStates(141, 142);
                  break;
               case 45:
                  if ((0x7fffffffffffffeL & l) != 0L)
                     jjCheckNAdd(46);
                  break;
               case 51:
                  if ((0xd7fffffed7ffffffL & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAdd(51);
                  break;
               case 61:
                  if ((0x1000000010000L & l) != 0L)
                     jjAddStates(143, 144);
                  break;
               case 63:
                  if ((0x200000002000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAdd(46);
                  break;
               case 65:
                  if (curChar == 115 && kind > 9)
                     kind = 9;
                  break;
               case 66:
                  if (curChar == 116 && kind > 9)
                     kind = 9;
                  break;
               case 67:
                  if (curChar == 100 && kind > 9)
                     kind = 9;
                  break;
               case 68:
                  if (curChar == 109 && kind > 9)
                     kind = 9;
                  break;
               case 69:
                  if (curChar == 101 && kind > 9)
                     kind = 9;
                  break;
               case 70:
                  if (curChar == 114)
                     jjCheckNAdd(69);
                  break;
               case 71:
                  if (curChar == 108 && kind > 9)
                     kind = 9;
                  break;
               case 72:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 71;
                  break;
               case 73:
                  if (curChar == 118)
                     jjCheckNAdd(69);
                  break;
               case 74:
                  if (curChar == 77)
                     jjAddStates(117, 134);
                  break;
               case 75:
               case 112:
               case 115:
               case 151:
               case 167:
               case 172:
               case 232:
               case 248:
               case 276:
                  if (curChar == 114)
                     jjCheckNAdd(34);
                  break;
               case 76:
               case 77:
               case 79:
               case 88:
               case 95:
               case 105:
               case 118:
               case 133:
               case 176:
               case 184:
               case 228:
               case 233:
               case 242:
               case 263:
               case 271:
               case 298:
                  if (curChar == 115)
                     jjCheckNAdd(34);
                  break;
               case 78:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 77;
                  break;
               case 80:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 79;
                  break;
               case 81:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 80;
                  break;
               case 82:
               case 116:
                  if (curChar == 82)
                     jjCheckNAdd(34);
                  break;
               case 84:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 83;
                  break;
               case 86:
                  if (curChar == 106)
                     jjCheckNAdd(34);
                  break;
               case 87:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 86;
                  break;
               case 89:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 88;
                  break;
               case 90:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 89;
                  break;
               case 91:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 90;
                  break;
               case 92:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 91;
                  break;
               case 93:
               case 153:
               case 217:
                  if (curChar == 103)
                     jjCheckNAdd(34);
                  break;
               case 94:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 93;
                  break;
               case 96:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 95;
                  break;
               case 97:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 96;
                  break;
               case 98:
               case 205:
               case 210:
               case 213:
               case 226:
                  if (curChar == 100)
                     jjCheckNAdd(34);
                  break;
               case 99:
               case 295:
                  if (curChar == 104)
                     jjCheckNAdd(34);
                  break;
               case 100:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 99;
                  break;
               case 101:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 100;
                  break;
               case 103:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 102;
                  break;
               case 104:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 103;
                  break;
               case 106:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 105;
                  break;
               case 107:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 106;
                  break;
               case 108:
               case 127:
               case 136:
               case 156:
               case 183:
               case 194:
               case 300:
                  if (curChar == 111)
                     jjCheckNAdd(34);
                  break;
               case 109:
               case 164:
               case 212:
               case 274:
               case 285:
               case 290:
               case 322:
               case 326:
               case 336:
                  if (curChar == 116)
                     jjCheckNAdd(34);
                  break;
               case 110:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 109;
                  break;
               case 111:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 110;
                  break;
               case 113:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 112;
                  break;
               case 114:
                  if (curChar == 68)
                     jjAddStates(111, 116);
                  break;
               case 119:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 118;
                  break;
               case 120:
               case 170:
               case 207:
               case 239:
                  if (curChar == 108)
                     jjCheckNAdd(34);
                  break;
               case 121:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 120;
                  break;
               case 122:
               case 201:
               case 203:
                  if (curChar == 99)
                     jjCheckNAdd(34);
                  break;
               case 123:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 122;
                  break;
               case 124:
                  if (curChar == 71)
                     jjAddStates(104, 110);
                  break;
               case 126:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 125;
                  break;
               case 128:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 127;
                  break;
               case 130:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 129;
                  break;
               case 131:
               case 266:
               case 314:
               case 316:
                  if (curChar == 118)
                     jjCheckNAdd(34);
                  break;
               case 132:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 131;
                  break;
               case 134:
                  if (curChar == 118)
                     jjstateSet[jjnewStateCnt++] = 133;
                  break;
               case 135:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 134;
                  break;
               case 137:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 136;
                  break;
               case 138:
               case 144:
               case 179:
               case 189:
               case 215:
               case 259:
               case 277:
               case 279:
               case 303:
               case 319:
               case 335:
                  if (curChar == 97)
                     jjCheckNAdd(34);
                  break;
               case 139:
                  if (curChar == 65)
                     jjAddStates(97, 103);
                  break;
               case 140:
               case 142:
               case 294:
                  if (curChar == 109)
                     jjCheckNAdd(34);
                  break;
               case 141:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 140;
                  break;
               case 143:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 142;
                  break;
               case 145:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 144;
                  break;
               case 146:
                  if (curChar == 122)
                     jjCheckNAdd(34);
                  break;
               case 147:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 146;
                  break;
               case 148:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 147;
                  break;
               case 149:
                  if (curChar == 107)
                     jjCheckNAdd(34);
                  break;
               case 150:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 149;
                  break;
               case 152:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 151;
                  break;
               case 154:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 153;
                  break;
               case 155:
                  if (curChar == 67)
                     jjAddStates(80, 96);
                  break;
               case 157:
               case 186:
               case 220:
               case 261:
               case 288:
                  if (curChar == 112)
                     jjCheckNAdd(34);
                  break;
               case 158:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 157;
                  break;
               case 159:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 158;
                  break;
               case 160:
               case 190:
               case 245:
                  if (curChar == 102)
                     jjCheckNAdd(34);
                  break;
               case 161:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 160;
                  break;
               case 162:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 161;
                  break;
               case 163:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 162;
                  break;
               case 165:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 164;
                  break;
               case 166:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 165;
                  break;
               case 168:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 167;
                  break;
               case 169:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 168;
                  break;
               case 171:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 170;
                  break;
               case 173:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 172;
                  break;
               case 174:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 173;
                  break;
               case 175:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 174;
                  break;
               case 177:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 176;
                  break;
               case 178:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 177;
                  break;
               case 180:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 179;
                  break;
               case 181:
               case 252:
               case 286:
               case 324:
                  if (curChar == 101)
                     jjCheckNAdd(34);
                  break;
               case 182:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 181;
                  break;
               case 185:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 184;
                  break;
               case 187:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 186;
                  break;
               case 188:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 187;
                  break;
               case 191:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 190;
                  break;
               case 192:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 191;
                  break;
               case 193:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 192;
                  break;
               case 195:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 194;
                  break;
               case 196:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 195;
                  break;
               case 198:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 197;
                  break;
               case 199:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 198;
                  break;
               case 200:
                  if (curChar == 73)
                     jjAddStates(76, 79);
                  break;
               case 202:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 201;
                  break;
               case 204:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 203;
                  break;
               case 206:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 205;
                  break;
               case 208:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 207;
                  break;
               case 209:
                  if (curChar == 76)
                     jjAddStates(72, 75);
                  break;
               case 211:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 210;
                  break;
               case 214:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 213;
                  break;
               case 216:
                  if (curChar == 66)
                     jjAddStates(68, 71);
                  break;
               case 218:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 217;
                  break;
               case 219:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 218;
                  break;
               case 221:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 220;
                  break;
               case 222:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 221;
                  break;
               case 223:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 222;
                  break;
               case 224:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 223;
                  break;
               case 225:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 224;
                  break;
               case 227:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 226;
                  break;
               case 229:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 228;
                  break;
               case 230:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 229;
                  break;
               case 231:
                  if (curChar == 74)
                     jjAddStates(63, 67);
                  break;
               case 234:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 233;
                  break;
               case 236:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 235;
                  break;
               case 238:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 237;
                  break;
               case 240:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 239;
                  break;
               case 241:
                  if (curChar == 80)
                     jjAddStates(56, 62);
                  break;
               case 243:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 242;
                  break;
               case 244:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 243;
                  break;
               case 246:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 245;
                  break;
               case 247:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 246;
                  break;
               case 249:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 248;
                  break;
               case 250:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 249;
                  break;
               case 251:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 250;
                  break;
               case 253:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 252;
                  break;
               case 254:
               case 310:
                  if (curChar == 121)
                     jjCheckNAdd(34);
                  break;
               case 255:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 254;
                  break;
               case 257:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 256;
                  break;
               case 258:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 257;
                  break;
               case 260:
                  if (curChar == 82)
                     jjAddStates(53, 55);
                  break;
               case 262:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 261;
                  break;
               case 264:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 263;
                  break;
               case 265:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 264;
                  break;
               case 267:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 266;
                  break;
               case 268:
                  if (curChar == 83)
                     jjAddStates(42, 52);
                  break;
               case 270:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 269;
                  break;
               case 272:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 271;
                  break;
               case 273:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 272;
                  break;
               case 275:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 274;
                  break;
               case 278:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 277;
                  break;
               case 280:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 279;
                  break;
               case 281:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 280;
                  break;
               case 284:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 283;
                  break;
               case 287:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 286;
                  break;
               case 289:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 288;
                  break;
               case 291:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 290;
                  break;
               case 292:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 291;
                  break;
               case 293:
                  if (curChar == 87)
                     jjAddStates(38, 41);
                  break;
               case 296:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 295;
                  break;
               case 297:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 296;
                  break;
               case 299:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 298;
                  break;
               case 301:
                  if (curChar == 121)
                     jjstateSet[jjnewStateCnt++] = 300;
                  break;
               case 302:
                  if (curChar == 70)
                     jjAddStates(36, 37);
                  break;
               case 304:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 303;
                  break;
               case 305:
               case 312:
                  if (curChar == 98)
                     jjCheckNAdd(34);
                  break;
               case 306:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 305;
                  break;
               case 307:
                  if (curChar == 75)
                     jjAddStates(34, 35);
                  break;
               case 309:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 308;
                  break;
               case 311:
                  if (curChar == 78)
                     jjAddStates(31, 33);
                  break;
               case 313:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 312;
                  break;
               case 315:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 314;
                  break;
               case 317:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 316;
                  break;
               case 318:
                  if (curChar == 79)
                     jjAddStates(27, 30);
                  break;
               case 320:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 319;
                  break;
               case 321:
                  if (curChar == 107)
                     jjstateSet[jjnewStateCnt++] = 320;
                  break;
               case 323:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 322;
                  break;
               case 325:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 324;
                  break;
               case 327:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 326;
                  break;
               case 328:
                  if (curChar == 84)
                     jjAddStates(25, 26);
                  break;
               case 330:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 329;
                  break;
               case 331:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 330;
                  break;
               case 332:
                  if (curChar == 120)
                     jjCheckNAdd(34);
                  break;
               case 333:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 332;
                  break;
               case 334:
                  if (curChar == 86)
                     jjAddStates(23, 24);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (int)(curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
               case 51:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAdd(51);
                  break;
               case 6:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjAddStates(135, 136);
                  break;
               case 10:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjAddStates(137, 138);
                  break;
               case 17:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjCheckNAddTwoStates(17, 18);
                  break;
               case 18:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 8)
                     kind = 8;
                  jjCheckNAdd(18);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 345 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   65, 66, 67, 68, 70, 72, 73, 57, 58, 61, 49, 50, 14, 33, 23, 24, 
   31, 20, 16, 21, 32, 23, 24, 335, 336, 331, 333, 321, 323, 325, 327, 313, 
   315, 317, 309, 310, 304, 306, 294, 297, 299, 301, 270, 273, 275, 276, 278, 281, 
   284, 285, 287, 289, 292, 262, 265, 267, 244, 247, 251, 253, 255, 258, 259, 232, 
   234, 236, 238, 240, 219, 225, 227, 230, 211, 212, 214, 215, 202, 204, 206, 208, 
   156, 159, 163, 166, 169, 171, 175, 178, 180, 182, 183, 185, 188, 189, 193, 196, 
   199, 141, 143, 145, 148, 150, 152, 154, 126, 128, 130, 132, 135, 137, 138, 115, 
   116, 117, 119, 121, 123, 75, 76, 78, 81, 82, 84, 85, 87, 92, 94, 97, 
   98, 101, 104, 107, 108, 111, 113, 6, 7, 10, 11, 16, 19, 43, 44, 62, 
   63, 
};
private static final boolean jjCanMove_0(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec2[i2] & l2) != 0L);
      default :
         if ((jjbitVec0[i1] & l1) != 0L)
            return true;
         return false;
   }
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[345];
private final int[] jjstateSet = new int[690];
protected char curChar;
/** Constructor. */
public GenTokerTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}

/** Constructor. */
public GenTokerTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 345; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
         matchedToken = jjFillToken();
         return matchedToken;
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
