/* Generated By:JavaCC: Do not edit this line. JsonTokerConstants.java */
package org.mitre.jcarafe.lexer;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JsonTokerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ENDPUNCT = 1;
  /** RegularExpression Id. */
  int WHITEEND = 2;
  /** RegularExpression Id. */
  int ABBREV = 3;
  /** RegularExpression Id. */
  int PUNCT = 4;
  /** RegularExpression Id. */
  int TOK = 5;
  /** RegularExpression Id. */
  int WHITE = 6;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<ENDPUNCT>",
    "<WHITEEND>",
    "<ABBREV>",
    "<PUNCT>",
    "<TOK>",
    "<WHITE>",
  };

}
