/* Generated By:JavaCC: Do not edit this line. JsonTokerTokenManager.java */
package org.mitre.jcarafe.lexer;

/** Token Manager. */
public class JsonTokerTokenManager implements JsonTokerConstants
{

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private int jjMoveStringLiteralDfa0_0()
{
   return jjMoveNfa_0(1, 0);
}
static final long[] jjbitVec0 = {
   0xfffffffffffffffeL, 0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec2 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 319;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((0x73ff0078ffffd9ffL & l) != 0L)
                  {
                     if (kind > 5)
                        kind = 5;
                     jjCheckNAdd(26);
                  }
                  else if ((0x2400L & l) != 0L)
                  {
                     if (kind > 6)
                        kind = 6;
                  }
                  else if ((0x100000200L & l) != 0L)
                  {
                     if (kind > 6)
                        kind = 6;
                     jjCheckNAdd(27);
                  }
                  else if ((0x8000400200000000L & l) != 0L)
                  {
                     if (kind > 1)
                        kind = 1;
                     jjCheckNAdd(0);
                  }
                  else if (curChar == 39)
                     jjAddStates(0, 5);
                  else if (curChar == 45)
                  {
                     if (kind > 5)
                        kind = 5;
                     jjCheckNAdd(19);
                  }
                  if ((0xfc00ff8600000000L & l) != 0L)
                  {
                     if (kind > 4)
                        kind = 4;
                     jjCheckNAdd(15);
                  }
                  else if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 5)
                        kind = 5;
                     jjCheckNAddStates(6, 10);
                  }
                  else if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 28;
                  else if (curChar == 36)
                     jjCheckNAddTwoStates(23, 24);
                  else if (curChar == 38)
                     jjstateSet[jjnewStateCnt++] = 17;
                  else if (curChar == 10)
                     jjCheckNAddTwoStates(3, 4);
                  if ((0x3ff700000000000L & l) != 0L)
                     jjCheckNAddTwoStates(23, 24);
                  else if (curChar == 33)
                     jjCheckNAddTwoStates(318, 314);
                  else if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 2;
                  else if (curChar == 63)
                     jjCheckNAddTwoStates(316, 314);
                  if (curChar == 46)
                     jjCheckNAddTwoStates(313, 314);
                  break;
               case 0:
                  if ((0x8000400200000000L & l) == 0L)
                     break;
                  if (kind > 1)
                     kind = 1;
                  jjCheckNAdd(0);
                  break;
               case 2:
                  if (curChar == 10)
                     jjCheckNAddTwoStates(3, 4);
                  break;
               case 3:
                  if (curChar == 13)
                     jjCheckNAdd(4);
                  break;
               case 4:
                  if (curChar != 10)
                     break;
                  if (kind > 2)
                     kind = 2;
                  jjCheckNAddTwoStates(3, 4);
                  break;
               case 6:
                  if (curChar == 39)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 8:
                  if (curChar == 46 && kind > 3)
                     kind = 3;
                  break;
               case 10:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 15:
                  if ((0xfc00ff8600000000L & l) == 0L)
                     break;
                  if (kind > 4)
                     kind = 4;
                  jjCheckNAdd(15);
                  break;
               case 16:
                  if (curChar == 38)
                     jjstateSet[jjnewStateCnt++] = 17;
                  break;
               case 18:
                  if (curChar == 59 && kind > 5)
                     kind = 5;
                  break;
               case 19:
                  if (curChar != 45)
                     break;
                  if (kind > 5)
                     kind = 5;
                  jjCheckNAdd(19);
                  break;
               case 21:
                  if (curChar == 46 && kind > 5)
                     kind = 5;
                  break;
               case 22:
                  if (curChar == 36)
                     jjCheckNAddTwoStates(23, 24);
                  break;
               case 23:
                  if ((0x3ff700000000000L & l) != 0L)
                     jjCheckNAddTwoStates(23, 24);
                  break;
               case 24:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 5)
                     kind = 5;
                  jjCheckNAddTwoStates(24, 25);
                  break;
               case 25:
                  if (curChar == 37 && kind > 5)
                     kind = 5;
                  break;
               case 26:
                  if ((0x73ff0078ffffd9ffL & l) == 0L)
                     break;
                  if (kind > 5)
                     kind = 5;
                  jjCheckNAdd(26);
                  break;
               case 27:
                  if ((0x100000200L & l) == 0L)
                     break;
                  if (kind > 6)
                     kind = 6;
                  jjCheckNAdd(27);
                  break;
               case 28:
                  if (curChar == 10 && kind > 6)
                     kind = 6;
                  break;
               case 29:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 28;
                  break;
               case 30:
                  if ((0x2400L & l) != 0L && kind > 6)
                     kind = 6;
                  break;
               case 31:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 5)
                     kind = 5;
                  jjCheckNAddStates(6, 10);
                  break;
               case 32:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(33, 36);
                  break;
               case 33:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 34;
                  break;
               case 34:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 35:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(36);
                  break;
               case 37:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 38;
                  break;
               case 39:
                  if (curChar == 39)
                     jjAddStates(0, 5);
                  break;
               case 256:
                  if (curChar == 32 && kind > 3)
                     kind = 3;
                  break;
               case 257:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 256;
                  break;
               case 311:
                  if (curChar == 46)
                     jjCheckNAddTwoStates(313, 314);
                  break;
               case 312:
                  if (curChar == 39 && kind > 1)
                     kind = 1;
                  break;
               case 313:
               case 316:
               case 318:
                  if (curChar == 39)
                     jjCheckNAdd(312);
                  break;
               case 314:
                  if (curChar == 34 && kind > 1)
                     kind = 1;
                  break;
               case 315:
                  if (curChar == 63)
                     jjCheckNAddTwoStates(316, 314);
                  break;
               case 317:
                  if (curChar == 33)
                     jjCheckNAddTwoStates(318, 314);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((0xd7fffffed7ffffffL & l) != 0L)
                  {
                     if (kind > 5)
                        kind = 5;
                     jjCheckNAdd(26);
                  }
                  if ((0x7fffffffffffffeL & l) != 0L)
                     jjCheckNAdd(21);
                  if ((0x7fffffffffffffeL & l) != 0L)
                  {
                     if (kind > 5)
                        kind = 5;
                     jjCheckNAdd(19);
                  }
                  if ((0x3800000128000000L & l) != 0L)
                  {
                     if (kind > 4)
                        kind = 4;
                     jjCheckNAdd(15);
                  }
                  else if (curChar == 86)
                     jjAddStates(11, 12);
                  else if (curChar == 84)
                     jjAddStates(13, 14);
                  else if (curChar == 79)
                     jjAddStates(15, 18);
                  else if (curChar == 78)
                     jjAddStates(19, 21);
                  else if (curChar == 75)
                     jjAddStates(22, 23);
                  else if (curChar == 70)
                     jjAddStates(24, 25);
                  else if (curChar == 87)
                     jjAddStates(26, 29);
                  else if (curChar == 83)
                     jjAddStates(30, 40);
                  else if (curChar == 82)
                     jjAddStates(41, 43);
                  else if (curChar == 80)
                     jjAddStates(44, 50);
                  else if (curChar == 74)
                     jjAddStates(51, 55);
                  else if (curChar == 66)
                     jjAddStates(56, 59);
                  else if (curChar == 76)
                     jjAddStates(60, 63);
                  else if (curChar == 73)
                     jjAddStates(64, 67);
                  else if (curChar == 67)
                     jjAddStates(68, 84);
                  else if (curChar == 65)
                     jjAddStates(85, 91);
                  else if (curChar == 71)
                     jjAddStates(92, 98);
                  else if (curChar == 68)
                     jjAddStates(99, 104);
                  else if (curChar == 77)
                     jjAddStates(105, 122);
                  else if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 13;
                  else if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 10;
                  else if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 5:
                  if (curChar == 116 && kind > 3)
                     kind = 3;
                  break;
               case 7:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 9:
               case 57:
               case 59:
                  if (curChar == 83)
                     jjCheckNAdd(8);
                  break;
               case 11:
                  if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 12:
               case 76:
               case 91:
               case 99:
               case 103:
               case 171:
               case 209:
               case 211:
               case 230:
               case 243:
               case 282:
               case 303:
                  if (curChar == 110)
                     jjCheckNAdd(8);
                  break;
               case 13:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 12;
                  break;
               case 14:
                  if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 15:
                  if ((0x3800000128000000L & l) == 0L)
                     break;
                  if (kind > 4)
                     kind = 4;
                  jjCheckNAdd(15);
                  break;
               case 17:
                  if ((0x7fffffffffffffeL & l) != 0L)
                     jjAddStates(123, 124);
                  break;
               case 19:
                  if ((0x7fffffffffffffeL & l) == 0L)
                     break;
                  if (kind > 5)
                     kind = 5;
                  jjCheckNAdd(19);
                  break;
               case 20:
                  if ((0x7fffffffffffffeL & l) != 0L)
                     jjCheckNAdd(21);
                  break;
               case 26:
                  if ((0xd7fffffed7ffffffL & l) == 0L)
                     break;
                  if (kind > 5)
                     kind = 5;
                  jjCheckNAdd(26);
                  break;
               case 36:
                  if ((0x1000000010000L & l) != 0L)
                     jjAddStates(125, 126);
                  break;
               case 38:
                  if ((0x200000002000L & l) == 0L)
                     break;
                  if (kind > 5)
                     kind = 5;
                  jjCheckNAdd(21);
                  break;
               case 40:
                  if (curChar == 115 && kind > 3)
                     kind = 3;
                  break;
               case 41:
                  if (curChar == 100 && kind > 3)
                     kind = 3;
                  break;
               case 42:
                  if (curChar == 109 && kind > 3)
                     kind = 3;
                  break;
               case 43:
                  if (curChar == 101 && kind > 3)
                     kind = 3;
                  break;
               case 44:
                  if (curChar == 114)
                     jjCheckNAdd(43);
                  break;
               case 45:
                  if (curChar == 108 && kind > 3)
                     kind = 3;
                  break;
               case 46:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 45;
                  break;
               case 47:
                  if (curChar == 118)
                     jjCheckNAdd(43);
                  break;
               case 48:
                  if (curChar == 77)
                     jjAddStates(105, 122);
                  break;
               case 49:
               case 86:
               case 89:
               case 125:
               case 141:
               case 146:
               case 206:
               case 222:
               case 250:
                  if (curChar == 114)
                     jjCheckNAdd(8);
                  break;
               case 50:
               case 51:
               case 53:
               case 62:
               case 69:
               case 79:
               case 92:
               case 107:
               case 150:
               case 158:
               case 202:
               case 207:
               case 216:
               case 237:
               case 245:
               case 272:
                  if (curChar == 115)
                     jjCheckNAdd(8);
                  break;
               case 52:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 51;
                  break;
               case 54:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 53;
                  break;
               case 55:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 54;
                  break;
               case 56:
               case 90:
                  if (curChar == 82)
                     jjCheckNAdd(8);
                  break;
               case 58:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 57;
                  break;
               case 60:
                  if (curChar == 106)
                     jjCheckNAdd(8);
                  break;
               case 61:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 60;
                  break;
               case 63:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 62;
                  break;
               case 64:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 63;
                  break;
               case 65:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 64;
                  break;
               case 66:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 65;
                  break;
               case 67:
               case 127:
               case 191:
                  if (curChar == 103)
                     jjCheckNAdd(8);
                  break;
               case 68:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 67;
                  break;
               case 70:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 69;
                  break;
               case 71:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 70;
                  break;
               case 72:
               case 179:
               case 184:
               case 187:
               case 200:
                  if (curChar == 100)
                     jjCheckNAdd(8);
                  break;
               case 73:
               case 269:
                  if (curChar == 104)
                     jjCheckNAdd(8);
                  break;
               case 74:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 73;
                  break;
               case 75:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 74;
                  break;
               case 77:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 76;
                  break;
               case 78:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 77;
                  break;
               case 80:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 79;
                  break;
               case 81:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 80;
                  break;
               case 82:
               case 101:
               case 110:
               case 130:
               case 157:
               case 168:
               case 274:
                  if (curChar == 111)
                     jjCheckNAdd(8);
                  break;
               case 83:
               case 138:
               case 186:
               case 248:
               case 259:
               case 264:
               case 296:
               case 300:
               case 310:
                  if (curChar == 116)
                     jjCheckNAdd(8);
                  break;
               case 84:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 83;
                  break;
               case 85:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 84;
                  break;
               case 87:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 86;
                  break;
               case 88:
                  if (curChar == 68)
                     jjAddStates(99, 104);
                  break;
               case 93:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 92;
                  break;
               case 94:
               case 144:
               case 181:
               case 213:
                  if (curChar == 108)
                     jjCheckNAdd(8);
                  break;
               case 95:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 94;
                  break;
               case 96:
               case 175:
               case 177:
                  if (curChar == 99)
                     jjCheckNAdd(8);
                  break;
               case 97:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 96;
                  break;
               case 98:
                  if (curChar == 71)
                     jjAddStates(92, 98);
                  break;
               case 100:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 99;
                  break;
               case 102:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 101;
                  break;
               case 104:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 103;
                  break;
               case 105:
               case 240:
               case 288:
               case 290:
                  if (curChar == 118)
                     jjCheckNAdd(8);
                  break;
               case 106:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 105;
                  break;
               case 108:
                  if (curChar == 118)
                     jjstateSet[jjnewStateCnt++] = 107;
                  break;
               case 109:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 108;
                  break;
               case 111:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 110;
                  break;
               case 112:
               case 118:
               case 153:
               case 163:
               case 189:
               case 233:
               case 251:
               case 253:
               case 277:
               case 293:
               case 309:
                  if (curChar == 97)
                     jjCheckNAdd(8);
                  break;
               case 113:
                  if (curChar == 65)
                     jjAddStates(85, 91);
                  break;
               case 114:
               case 116:
               case 268:
                  if (curChar == 109)
                     jjCheckNAdd(8);
                  break;
               case 115:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 114;
                  break;
               case 117:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 116;
                  break;
               case 119:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 118;
                  break;
               case 120:
                  if (curChar == 122)
                     jjCheckNAdd(8);
                  break;
               case 121:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 120;
                  break;
               case 122:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 121;
                  break;
               case 123:
                  if (curChar == 107)
                     jjCheckNAdd(8);
                  break;
               case 124:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 123;
                  break;
               case 126:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 125;
                  break;
               case 128:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 127;
                  break;
               case 129:
                  if (curChar == 67)
                     jjAddStates(68, 84);
                  break;
               case 131:
               case 160:
               case 194:
               case 235:
               case 262:
                  if (curChar == 112)
                     jjCheckNAdd(8);
                  break;
               case 132:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 131;
                  break;
               case 133:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 132;
                  break;
               case 134:
               case 164:
               case 219:
                  if (curChar == 102)
                     jjCheckNAdd(8);
                  break;
               case 135:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 134;
                  break;
               case 136:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 135;
                  break;
               case 137:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 136;
                  break;
               case 139:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 138;
                  break;
               case 140:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 139;
                  break;
               case 142:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 141;
                  break;
               case 143:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 142;
                  break;
               case 145:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 144;
                  break;
               case 147:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 146;
                  break;
               case 148:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 147;
                  break;
               case 149:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 148;
                  break;
               case 151:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 150;
                  break;
               case 152:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 151;
                  break;
               case 154:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 153;
                  break;
               case 155:
               case 226:
               case 260:
               case 298:
                  if (curChar == 101)
                     jjCheckNAdd(8);
                  break;
               case 156:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 155;
                  break;
               case 159:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 158;
                  break;
               case 161:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 160;
                  break;
               case 162:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 161;
                  break;
               case 165:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 164;
                  break;
               case 166:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 165;
                  break;
               case 167:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 166;
                  break;
               case 169:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 168;
                  break;
               case 170:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 169;
                  break;
               case 172:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 171;
                  break;
               case 173:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 172;
                  break;
               case 174:
                  if (curChar == 73)
                     jjAddStates(64, 67);
                  break;
               case 176:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 175;
                  break;
               case 178:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 177;
                  break;
               case 180:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 179;
                  break;
               case 182:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 181;
                  break;
               case 183:
                  if (curChar == 76)
                     jjAddStates(60, 63);
                  break;
               case 185:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 184;
                  break;
               case 188:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 187;
                  break;
               case 190:
                  if (curChar == 66)
                     jjAddStates(56, 59);
                  break;
               case 192:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 191;
                  break;
               case 193:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 192;
                  break;
               case 195:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 194;
                  break;
               case 196:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 195;
                  break;
               case 197:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 196;
                  break;
               case 198:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 197;
                  break;
               case 199:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 198;
                  break;
               case 201:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 200;
                  break;
               case 203:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 202;
                  break;
               case 204:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 203;
                  break;
               case 205:
                  if (curChar == 74)
                     jjAddStates(51, 55);
                  break;
               case 208:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 207;
                  break;
               case 210:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 209;
                  break;
               case 212:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 211;
                  break;
               case 214:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 213;
                  break;
               case 215:
                  if (curChar == 80)
                     jjAddStates(44, 50);
                  break;
               case 217:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 216;
                  break;
               case 218:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 217;
                  break;
               case 220:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 219;
                  break;
               case 221:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 220;
                  break;
               case 223:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 222;
                  break;
               case 224:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 223;
                  break;
               case 225:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 224;
                  break;
               case 227:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 226;
                  break;
               case 228:
               case 284:
                  if (curChar == 121)
                     jjCheckNAdd(8);
                  break;
               case 229:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 228;
                  break;
               case 231:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 230;
                  break;
               case 232:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 231;
                  break;
               case 234:
                  if (curChar == 82)
                     jjAddStates(41, 43);
                  break;
               case 236:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 235;
                  break;
               case 238:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 237;
                  break;
               case 239:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 238;
                  break;
               case 241:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 240;
                  break;
               case 242:
                  if (curChar == 83)
                     jjAddStates(30, 40);
                  break;
               case 244:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 243;
                  break;
               case 246:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 245;
                  break;
               case 247:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 246;
                  break;
               case 249:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 248;
                  break;
               case 252:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 251;
                  break;
               case 254:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 253;
                  break;
               case 255:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 254;
                  break;
               case 258:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 257;
                  break;
               case 261:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 260;
                  break;
               case 263:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 262;
                  break;
               case 265:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 264;
                  break;
               case 266:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 265;
                  break;
               case 267:
                  if (curChar == 87)
                     jjAddStates(26, 29);
                  break;
               case 270:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 269;
                  break;
               case 271:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 270;
                  break;
               case 273:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 272;
                  break;
               case 275:
                  if (curChar == 121)
                     jjstateSet[jjnewStateCnt++] = 274;
                  break;
               case 276:
                  if (curChar == 70)
                     jjAddStates(24, 25);
                  break;
               case 278:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 277;
                  break;
               case 279:
               case 286:
                  if (curChar == 98)
                     jjCheckNAdd(8);
                  break;
               case 280:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 279;
                  break;
               case 281:
                  if (curChar == 75)
                     jjAddStates(22, 23);
                  break;
               case 283:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 282;
                  break;
               case 285:
                  if (curChar == 78)
                     jjAddStates(19, 21);
                  break;
               case 287:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 286;
                  break;
               case 289:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 288;
                  break;
               case 291:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 290;
                  break;
               case 292:
                  if (curChar == 79)
                     jjAddStates(15, 18);
                  break;
               case 294:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 293;
                  break;
               case 295:
                  if (curChar == 107)
                     jjstateSet[jjnewStateCnt++] = 294;
                  break;
               case 297:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 296;
                  break;
               case 299:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 298;
                  break;
               case 301:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 300;
                  break;
               case 302:
                  if (curChar == 84)
                     jjAddStates(13, 14);
                  break;
               case 304:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 303;
                  break;
               case 305:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 304;
                  break;
               case 306:
                  if (curChar == 120)
                     jjCheckNAdd(8);
                  break;
               case 307:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 306;
                  break;
               case 308:
                  if (curChar == 86)
                     jjAddStates(11, 12);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (int)(curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
               case 26:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 5)
                     kind = 5;
                  jjCheckNAdd(26);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 319 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   40, 41, 42, 44, 46, 47, 32, 33, 36, 24, 25, 309, 310, 305, 307, 295, 
   297, 299, 301, 287, 289, 291, 283, 284, 278, 280, 268, 271, 273, 275, 244, 247, 
   249, 250, 252, 255, 258, 259, 261, 263, 266, 236, 239, 241, 218, 221, 225, 227, 
   229, 232, 233, 206, 208, 210, 212, 214, 193, 199, 201, 204, 185, 186, 188, 189, 
   176, 178, 180, 182, 130, 133, 137, 140, 143, 145, 149, 152, 154, 156, 157, 159, 
   162, 163, 167, 170, 173, 115, 117, 119, 122, 124, 126, 128, 100, 102, 104, 106, 
   109, 111, 112, 89, 90, 91, 93, 95, 97, 49, 50, 52, 55, 56, 58, 59, 
   61, 66, 68, 71, 72, 75, 78, 81, 82, 85, 87, 17, 18, 37, 38, 
};
private static final boolean jjCanMove_0(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec2[i2] & l2) != 0L);
      default :
         if ((jjbitVec0[i1] & l1) != 0L)
            return true;
         return false;
   }
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[319];
private final int[] jjstateSet = new int[638];
protected char curChar;
/** Constructor. */
public JsonTokerTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}

/** Constructor. */
public JsonTokerTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 319; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
         matchedToken = jjFillToken();
         return matchedToken;
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
