/* Generated By:JavaCC: Do not edit this line. WhiteSpaceToker2Constants.java */
package org.mitre.jcarafe.lexer;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface WhiteSpaceToker2Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITEENDLONG = 1;
  /** RegularExpression Id. */
  int WHITEEND = 2;
  /** RegularExpression Id. */
  int PUNCT = 3;
  /** RegularExpression Id. */
  int TOK = 4;
  /** RegularExpression Id. */
  int WHITE = 5;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITEENDLONG>",
    "<WHITEEND>",
    "<PUNCT>",
    "<TOK>",
    "<WHITE>",
  };

}
