/* Generated By:JavaCC: Do not edit this line. WhiteSpaceTokerConstants.java */
package org.mitre.jcarafe.lexer;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface WhiteSpaceTokerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITEEND = 1;
  /** RegularExpression Id. */
  int TOK = 2;
  /** RegularExpression Id. */
  int WHITE = 3;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITEEND>",
    "<TOK>",
    "<WHITE>",
  };

}
