/**
 * JavaCC file
 */
 
options {
  JDK_VERSION = "1.6";
  STATIC = false;
  BUILD_PARSER = true;
  UNICODE_INPUT = true;
}
PARSER_BEGIN(GenToker)
package org.mitre.jcarafe.lexer;

public class GenToker {
  public static void main(String args[]) throws ParseException {
    System.out.println("Main not implemented");
  }
}
PARSER_END(GenToker)
SKIP :
{  < #ST: "<" >
| < #EN: ">" >
| < #ENST: "</" >

}

TOKEN : /* OPERATORS */
{
    < ENDPUNCT: (([".","!","?"])+ | ".''" | "?''" | ".\"" | "?\"" | "!''" | "!\"") >
|   < WHITEEND: (("\r")? "\n") (("\r")? "\n")+ >
|   < TAGEND: ( < ENST > ( ~["<",">"] )+ < EN > ) >
|   < TAGSTART: ( < ST > ( ~["<",">"] )+ < EN > ) >
|   < URL: ( ((["a"-"z"])+ ":") (((("/"){1,3}) | (["a"-"z","0"-"9","%"])) (("www" (["0"-"9"]){0,3} ".") | ((["a"-"z","0"-"9",".","-"])+ "." (["a"-"z"]){2,4} "/" ))) ((~[" ","\t","\n","\r","(",")","<",">"])+) ((~[" ","\t","\n","\r","`","'","[","]","!","(",")","{","}",";",":","\"",".",",","<",">","?"])+)) > 
|   < ABBREV: ( "'s"|"'t"|"'d"|"'m"|"'re"|"'ll"|"'ve"
	|"U.S."|"Mr."|"Ms."|"Dr."|"Gen."|"Mrs."|"Adm."|"Co."|"Inc."|"Ltd."|"Corp."|"Mass."|"Calif."|"MR."|"MRS."|"DR."|"MS."
	|"Adm."|"Brig."|"Capt."|"Cmdr."|"Col."|"Comdr."|"Dn."|"Drs."|"Geo."|"Gen."|"Gov."|"Govs."|"Hon."|"Jr."|"Lt."|"Maj."
	|"Messrs."|"Pres."|"Prof."|"Profr."|"Rep."|"Reps."|"Rev."|"Sen."|"Sens."|"Sgt."|"Sr."|"Sra."|"Srta."|"ST. "|"St."|"Ste."
	|"Wm."|"Geo."|"Jos."|"Chas."|"Bancorp."|"Bhd."|"Bros."|"Cia."|"Cie."|"Co."|"Cos."|"Corp."|"Inc."|"Ltd."|"Mfg."|"Pte."|"Pty."
	|"Ala."|"Ariz."|"Ark."|"Ca."|"Calif."|"Colo."|"Conn."|"Del."|"Fla."|"Ga."|"Ind."|"Ill."|"Kan."|"Ky."|"La."
	|"Mass."|"Md."|"Mich."|"Minn."|"Miss."|"Mo."|"Mont."|"Neb."|"Nev."|"Okla."|"Ont."|"Ore."|"Penn."|"Pa."|"Tenn."|"Tex."
	|"Va."|"Vt."|"Wash."|"Wis."|"Wyo."|"Jan."|"Feb."|"Mar."|"Apr."|"Jun."|"Jul."|"Aug."|"Sep."|"Sept."|"Oct."|"Nov."|"Dec.") >
| 	< PUNCT: ( [".",";","(",")",",","!","?","`","\"","{","}","'",":","*","+","=","|","[","]","&"])+ >
|   < TOK: ( ( "&" (["A"-"z"])+ ";" ) |
    /*   ((["A"-"z"])+ "-" (["A"-"z"])+) | */
	((["0"-"9"])?["0"-"9"](":" ["0"-"9"] ["0"-"9"] )? ["P","p"](".")? ["M","m"] (".")?) | ( ["A"-"z"] "." ) |
	(( "$" )? ( ["0"-"9",",",".","-"])* (["0"-"9"])+ ( "%" )? ) |
	(( ~[" ","\r","\n","\t","<",".",";","(",")",",","!","?","`","\"","{","}","'",":","*","+","[","]","&"] )+ )) >
|   < WHITE: ( ([" ","\t"])+ | ((["\r","\n"]) | ("\r\n")) ) >
    }
