/**
 * JavaCC file
 */
 
options {
  JDK_VERSION = "1.6";
  STATIC = false;
  BUILD_PARSER = true;
  UNICODE_INPUT = true;
}
PARSER_BEGIN(JsonToker)
package org.mitre.jcarafe.lexer;

public class JsonToker {
  public static void main(String args[]) throws ParseException {
    System.out.println("Main not implemented");
  }
}
PARSER_END(JsonToker)

TOKEN : /* OPERATORS */
{
    < ENDPUNCT: (([".","!","?"])+ | ".''" | "?''" | ".\"" | "?\"" | "!''" | "!\"" | "\u002e" | "\uff0e" | "\u06d4" | "\uff61") >
|   < WHITEEND: (("\r")? "\n") (("\r")? "\n")+ >
|   < ABBREV: ( "'s"|"n't"|"'d"|"'m"|"'re"|"'ll"|"'ve"
	|"u.s."|"U.S."|"Mr."|"Ms."|"Dr."|"Gen."|"Mrs."|"Adm."|"Co."|"Inc."|"Ltd."|"Corp."|"Mass."|"Calif."|"MR."|"MRS."|"DR."|"MS."
	|"Adm."|"Brig."|"Capt."|"Cmdr."|"Col."|"Comdr."|"Dn."|"Drs."|"Geo."|"Gen."|"Gov."|"Govs."|"Hon."|"Jr."|"Lt."|"Maj."
	|"Messrs."|"Pres."|"Prof."|"Profr."|"Rep."|"Reps."|"Rev."|"Sen."|"Sens."|"Sgt."|"Sr."|"Sra."|"Srta."|"ST. "|"St."|"Ste."
	|"Wm."|"Geo."|"Jos."|"Chas."|"Bancorp."|"Bhd."|"Bros."|"Cia."|"Cie."|"Co."|"Cos."|"Corp."|"Inc."|"Ltd."|"Mfg."|"Pte."|"Pty."
	|"Ala."|"Ariz."|"Ark."|"Ca."|"Calif."|"Colo."|"Conn."|"Del."|"Fla."|"Ga."|"Ind."|"Ill."|"Kan."|"Ky."|"La."
	|"Mass."|"Md."|"Mich."|"Minn."|"Miss."|"Mo."|"Mont."|"Neb."|"Nev."|"Okla."|"Ont."|"Ore."|"Penn."|"Pa."|"Tenn."|"Tex."
	|"Va."|"Vt."|"Wash."|"Wis."|"Wyo."|"Jan."|"Feb."|"Mar."|"Apr."|"Jun."|"Jul."|"Aug."|"Sep."|"Sept."|"Oct."|"Nov."|"Dec.") >
| 	< PUNCT: ( [".",";","(",")",",","!","?","`","\"","{","}","'",":","*","+","=","|","[","]","-","/","<",">"])+ >
|   < TOK: ( ( "&" (["A"-"z"])+ ";" ) |
     ((["A"-"z","-"])+) |
	((["0"-"9"])?["0"-"9"](":" ["0"-"9"] ["0"-"9"] )? ["P","p"](".")? ["M","m"] (".")?) | ( ["A"-"z"] "." ) |
	(( "$" )? ( ["0"-"9",",",".","-"])* (["0"-"9"])+ ( "%" )? ) |
	(( ~[" ","\r","\n","\t",".",";","(",")",",","!","?","`","\"","{","}","'",":","*","+","[","]","/","-"] )+ )) >
|   < WHITE: ( ([" ","\t"])+ | ((["\r","\n"]) | ("\r\n")) ) >

    
}
