/**
 * JavaCC file
 *  
 * Simple whitespace tokenizer.  Useful when tokenization has already occurred and tokens are white-space delimited.
 */
 
options {
  JDK_VERSION = "1.6";
  STATIC = false;
  BUILD_PARSER = true;
  UNICODE_INPUT = true;
}
PARSER_BEGIN(WhiteSpaceToker)
package org.mitre.jcarafe.lexer;

public class WhiteSpaceToker {
  public static void main(String args[]) throws ParseException {
    System.out.println("Main not implemented");
  }
}
PARSER_END(WhiteSpaceToker)

TOKEN : /* OPERATORS */
{
    < WHITEEND: ( (("\r")? "\n")+ ) >
|   < TOK: ( (~[" ","\r","\n","\t"])+ ) >
|   < WHITE: ( ([" ","\t","\r"])+ ) >
    
}
